### ISSUE TITLE
Continue if resolved directories don't exist

### ISSUE THREAD

**Issue by MaximDevoir** [GeKorm/webpack-permissions-plugin#3]
#### Current Behavior

If a directory doesn't exist, the program will throw an error and exit from the
webpack build process, throwing the following error from the subsequent plugin
setup:

`Error: ENOENT: no such file or directory, stat '/. . ./path/does/not/exist'`

plugin setup:

```JS
// file:webpack config
plugins: [
  ...
  new PermissionsOutputPlugin({
    buildFolders: [{
      path: path.resolve(__dirname, 'path/does/not/exist'),
      dirMode: '775',
      fileMode: '664'
    }]
  })
]

```

#### Expected Behavior

The program should catch and ignore errors about non-existent path.

#### Notes

Some quick testing and I found this bug doesn't seem to affect `buildFiles`,
only `buildFolders`.

**Comment by GeKorm** [comment]
Thanks for the detailed description! I'll fix this as soon as possible.

**Comment by GeKorm** [comment]
1.0.6 has been published with a fix :) It now logs a warning instead of throwing.
