### ISSUE TITLE
Not the latest version available on npm

### ISSUE THREAD

**Issue by vitchioto** [GeKorm/webpack-permissions-plugin#8]
Hello there :)

it seems, this commit: https://github.com/GeKorm/webpack-permissions-plugin/commit/2d65704b7a31e0125c8553996d4684cae56bba47

was not released...

if I install the package from npm (https://www.npmjs.com/package/webpack-permissions-plugin) it gives me version 1.0.7, which should be the latest one, but the update from the commit is missing there, as you can see here:

https://www.dropbox.com/s/tuquoje6tysrrqo/webpack-permissions-plugin.png?dl=0

Can you, please, have a look at it, when you have a moment? :)

Thanks

**Comment by GeKorm** [comment]
Just published v1.0.8 which includes your file selection fix. Thanks!
